name: 'Go'

# trigger on direct push or merge
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./code

    runs-on: ubuntu-latest
    steps:
      # checkout repo
    - uses: actions/checkout@v3
      # as it says
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
      # do something
    - name: Build
      run: go build -v ./...